# Generated by Django 5.2.3 on 2025-06-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='passing_year',
            field=models.IntegerField(null=True),
        ),
    ]
