# Generated by Django 5.2.3 on 2025-06-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_customusermodel_passing_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='media/image'),
        ),
    ]
